---
apiVersion: v1
kind: Namespace
metadata:
  name: hydra

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
  namespace: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra
  template:
    metadata:
      labels:
        app: hydra
    spec:
      automountServiceAccountToken: false
      containers:
        - name: hydra
          image: docker.io/oryd/hydra:v2.2.0
          args:
            - serve
            - all
            - --dev
          env:
            - name: URLS_SELF_ISSUER
              value: http://hydra:4444
            - name: URLS_CONSENT
              value: http://consent:3000/consent
            - name: URLS_LOGIN
              value: http://consent:3000/login
            - name: URLS_LOGOUT
              value: http://consent:3000/logout
            - name: DSN
              value: memory
            - name: SECRETS_SYSTEM
              value: youReallyNeedToChangeThis
            - name: OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES
              value: public
            - name: OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
              value: youReallyNeedToChangeThis
            - name: STRATEGIES_ACCESS_TOKEN
              value: jwt
            - name: LOG_LEAK_SENSITIVE_VALUES
              value: "true"
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          ports:
            - containerPort: 4444
              name: public
              protocol: TCP
            - containerPort: 4445
              name: admin
              protocol: TCP
            - containerPort: 5555
              name: token
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 400m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: hydra
  namespace: hydra
spec:
  type: ClusterIP
  ports:
    - port: 4444
      targetPort: public
      name: public
    - port: 4445
      targetPort: admin
      name: admin
    - port: 5555
      targetPort: token
      name: token
  selector:
    app: hydra

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consent
  namespace: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consent
  template:
    metadata:
      labels:
        app: consent
    spec:
      automountServiceAccountToken: false
      containers:
        - name: consent
          image: docker.io/jlevesy/hail-hydra:v0.0.1
          args:
            - -a
            - http://hydra:4445
            - -b
            - :3000
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          ports:
            - containerPort: 3000
              name: consent
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: consent
  namespace: hydra
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: consent
      name: consent
  selector:
    app: consent

