---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: weather-api-wrr
  namespace: apps
spec:
  weighted:
    services:
      - name: weather-app
        port: 3000
        weight: 1
      - name: weather-app-forecast
        port: 3000
        weight: 1

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: weather-api-v1
  namespace: apps
spec:
  release: v1.0.0

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: weather-api-v1-1
  namespace: apps
spec:
  release: v1.1.0

---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: weather-api
  namespace: apps
spec:
  versions:
    - name: weather-api-v1
    - name: weather-api-v1-1

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: weather-api
  namespace: apps
spec:
  apis:
  - name: weather-api
  everyone: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weather-api
  namespace: apps
  annotations:
    hub.traefik.io/api-version: weather-api-v1
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`api.docker.localhost`) && PathPrefix(`/weather`)
    kind: Rule
    services:
    - name: weather-api-wrr
      port: 3000
      kind: TraefikService
