---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: weather-api-v1
  namespace: traefik-hub
spec:
  release: v1.0.0

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: weather-api-v1-1
  namespace: traefik-hub
spec:
  release: v1.1.0

---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: weather-api
  namespace: traefik-hub
spec:
  versions:
    - name: weather-api-v1
    - name: weather-api-v1-1

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: weather-api
  namespace: traefik-hub
spec:
  apis:
  - name: weather-api
  everyone: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weather-api
  namespace: traefik-hub
  annotations:
    hub.traefik.io/api-version: weather-api-v1
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`api.docker.localhost`) && PathPrefix(`/weather`)
    kind: Rule
    services:
    - name: weather-app
      port: 3000

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weather-api-v1-1
  namespace: traefik-hub
  annotations:
    hub.traefik.io/api-version: weather-api-v1-1
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`api.docker.localhost`) && PathPrefix(`/weather`) && Header(`X-Version`, `preview`)
    kind: Rule
    services:
    - name: weather-app-forecast
      port: 3000
