---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: weather-api-forecast
  namespace: apps
spec:
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: http://api.docker.localhost

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: weather-api-forecast
  namespace: apps
spec:
  apis:
  - name: weather-api-forecast
  everyone: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weather-api-forecast
  namespace: apps
  annotations:
    hub.traefik.io/api: weather-api-forecast
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`api.docker.localhost`) && PathPrefix(`/forecast`)
    kind: Rule
    services:
    - name: weather-app-forecast
      port: 3000
