---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: admin-api
  namespace: admin
spec: {}

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: admin
  namespace: admin
spec:
  groups:
    - admin
  apis: # <=== Select only this API
    - name: admin-api

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: admin-api
  namespace: admin
  annotations:
    hub.traefik.io/api: admin-api
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`api.docker.localhost`) && PathPrefix(`/admin`)
    kind: Rule
    services:
    - name: admin-app
      port: 3000

