---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: weather-api
  namespace: traefik-hub
  labels:
    subscription: standard
spec:
  openApiSpec:
    path: /openapi.yaml
    operationSets:
      - name: get-forecast
        matchers:
          - pathPrefix: "/weather"
            methods: [ "GET" ]
      - name: patch-forecast
        matchers:
          - pathPrefix: "/weather"
            methods: [ "PATCH" ]

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: weather-api-external
  namespace: traefik-hub
spec:
  groups:
    - external
  apiSelector:
    matchLabels:
      subscription: standard
  operationFilter:
    include:
      - get-forecast

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: weather-api-admin
  namespace: traefik-hub
spec:
  groups:
    - admin
  apiSelector:
    matchLabels:
      subscription: standard
  operationFilter:
    include:
      - get-forecast
      - patch-forecast

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weather-api
  namespace: traefik-hub
  annotations:
    hub.traefik.io/api: weather-api
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`api.docker.localhost`) && PathPrefix(`/weather`)
    kind: Rule
    services:
    - name: weather-app
      port: 3000

